project:
  name: can-ids-full-cloud-pipeline
  environment: cloud

gcp:
  project_id: project-e6de9b55-41d5-4f13-ae0
  region: europe-southwest1
  bucket_name: can-ids-data
  temp_bucket: can-ids-data

storage:
  raw_prefix: raw/
  config_path: config/config.yml
  dbc_path: dbc/hyundai_2015_ccan.dbc

bigquery:
  location: europe-southwest1

  datasets:
    bronze: can_ids_bronze
    silver: can_ids_silver
    gold: can_ids_gold
    audit: can_ids_audit

  tables:
    bronze_raw: messages_raw
    bronze_rejected: messages_rejected

    silver_clean: messages_clean
    silver_iat: messages_with_iat
    silver_decoded: messages_decoded
    quality_silver_report: quality_silver_report
    quality_silver_alerts: quality_silver_alerts

    
    gold_features_window: gold_features_window
    can_id_profile: can_id_profile
    dbc_messages_reference: dbc_messages_reference


    pipeline_runs: pipeline_runs
    file_processing_status: file_processing_status
    quality_reports: quality_reports

can_rules:
  arbitration_id_min: 0
  arbitration_id_max: 2047
  dlc_min: 0
  dlc_max: 8
  accepted_labels: [0, 1]

ingestion:
  skip_existing_files: true